url: "https://lndh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/breadcrumb-menu-generator" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

page_gen:
- data: 'links'
  template: 'menu'
  name: 'title'
  dir: ''