name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - uses: actions/checkout@master

      - name: merge master into gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: gh-pages
          github_token: ${{ github.token }}


      - name: remove all files, but keep html site
        run: |
          shopt -s extglob
          rm -v -r !("_site")
          shopt -u extglob
          cd _site
          mv * ../
          cd ..
          rm -r _site

      - name: push
        uses: actions-x/commit@v2
        with:
          email: me@example.com
          name: GitHub Actions Autocommitter
          branch: gh-pages
          files: .
          repository: https://github.com/LndH/breadcrumb-test
          token: ${{ secrets.MY_SECRET_TOKEN }}

