name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # checkout master
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1

      - name: push changes on master
        uses: actions-x/commit@v2
        with:
          email: me@example.com
          name: GitHub Actions Autocommitter
          branch: master
          files: .
          repository: https://github.com/LndH/breadcrumb-test
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

     


    

